### PR TITLE
PR#13 Add support for NC-Token

### PR DESCRIPTION
**Pull request by shalak**

### CODE REVIEW

**Comment by arnowelzel** [comment]
Why did you close this PR? Doesn't it work?

**Comment by shalak** [comment]
> Why did you close this PR? Doesn't it work?

Heh, you're fast :) I've messed up my fork, needed to clear it up. Nevertheless, there are problems, let's continue the discussion over at PR#15

**Comment by shalak** [comment]
@arnowelzel 

> Why did you close this PR? Doesn't it work?

Heh, you're fast :) I've messed up my fork, needed to clear it up. Nevertheless, there are problems, let's continue the discussion over at PR#15

**Comment by arnowelzel** [comment]
I'm open for discussion. Just let me know what problems you are talking about at https://github.com/arnowelzel/netdata-nextcloud/pull/15

**Pull request closed without merging**
